export const classList = [
	{label:'전체', value:'all'},
	{label:'1분반', value:'class1'},
	{label:'2분반', value:'class2'},
	{label:'3분반', value:'class3'},
	{label:'4분반', value:'class4'},
]
export const profileList = [
	{label:'전체', value:'all'},
	{label:'프로필', value:'profile'},
	{label:'프사', value:'photo'},
]
export const genderList = [
	{label:'전체', value:'all'},
	{label:'남자', value:'boy'},
	{label:'여자', value:'girl'},
]
export const imgList = [
	{name:'1김민준.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1김민준프사.png', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1나현호.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1나현호프사.png', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1노건호.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1노건호프사.png', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1박관준.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1박관준프사.png', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1배윤아.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1배윤아프사.png', class_type:'class1', profile_type:'photo', gender_type:'girl'},
	{name:'1서정인.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1서정인프사.png', class_type:'class1', profile_type:'photo', gender_type:'girl'},
	{name:'1신우혁.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1심승훈.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1심승훈프사.png', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1은주연.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1이은민.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1이은민프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'girl'},
	{name:'1이재현.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1이재현프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1이현정.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1이현정프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'girl'},
	{name:'1임선민.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1임선민프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'girl'},
	{name:'1최민성.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1최민성프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1최치원.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1최치원프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1한다인.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1한정진.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1한정진프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'1황지영.png', class_type:'class1', profile_type:'profile', gender_type:'girl'},
	{name:'1황지영프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'girl'},
	{name:'1황지훈.png', class_type:'class1', profile_type:'profile', gender_type:'boy'},
	{name:'1황지훈프사.jpg', class_type:'class1', profile_type:'photo', gender_type:'boy'},
	{name:'2김규민.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2김규민프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2김제형.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2김제형프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2김지민.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2김지민프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2김지연.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2김지연프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2김채현.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2김채현프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2류주형.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2류주형프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2박경리.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2박경리프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2박세린.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2박세린프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2박세영.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2박세영프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2박지연.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2박지연프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2백소영.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2백소영프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2석인호.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2석인호프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2윤종범.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2윤종범프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2이솔민.png', class_type:'class2', profile_type:'profile', gender_type:'girl'},
	{name:'2이솔민프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'girl'},
	{name:'2이윤제.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2이윤제프사.png', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2장근영.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2장근영프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2조재민.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2조재민프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2주민재.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2한재영.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2한재영프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'2함봉구.png', class_type:'class2', profile_type:'profile', gender_type:'boy'},
	{name:'2함봉구프사.jpg', class_type:'class2', profile_type:'photo', gender_type:'boy'},
	{name:'3김동현.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3김동현프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3김승준.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3김승준프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3김재헌.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3김한준.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3김한준프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3박기람.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3박기람프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3박성준.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3박성준프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3박재현.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3박지민.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3박지민프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3박지헌.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3박지헌프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3백서경.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3백서경프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3윤신이.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3윤신이프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3이다인.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3이다인프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3이서진.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3이서진프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3이연재.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3이연재프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3이재현.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3이재현프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3이창민.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3이창민프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3임하민.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3임하민프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3장서우.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'3장서우프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'boy'},
	{name:'3하예영.png', class_type:'class3', profile_type:'profile', gender_type:'girl'},
	{name:'3하예영프사.jpg', class_type:'class3', profile_type:'photo', gender_type:'girl'},
	{name:'3황광호.png', class_type:'class3', profile_type:'profile', gender_type:'boy'},
	{name:'4강시연.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4강시연프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'girl'},
	{name:'4구자윤.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4구자윤프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4권민성.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4권민성프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4김병주.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4김병주프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4김수연.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4김수연프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'girl'},
	{name:'4김준형.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4김준형프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4김현승.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4김현승프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4마서진.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4마서진프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'girl'},
	{name:'4박보연.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4박보연프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'girl'},
	{name:'4박진웅.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4박진웅프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4백재호.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4백재호프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4빈서윤.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4이건.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4이건프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4이중권.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4이중권프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
	{name:'4이지원.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4이지원프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'girl'},
	{name:'4이지은.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4이지은프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'girl'},
	{name:'4정태희.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4하승원.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4하승원프사.jpg', class_type:'class4', profile_type:'photole', gender_type:'boy'},
	{name:'4한유진.png', class_type:'class4', profile_type:'profile', gender_type:'girl'},
	{name:'4한유진프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'girl'},
	{name:'4황정현.png', class_type:'class4', profile_type:'profile', gender_type:'boy'},
	{name:'4황정현프사.jpg', class_type:'class4', profile_type:'photo', gender_type:'boy'},
]
export const cardList = [
	{name: '몰캠 전체 느좋 프로필 월드컵', class_type: 'all', profile_type: 'profile', gender_type: 'all', id: 'a7c4ba8e-bd77-45f9-9aed-df315c543770'},
	{name: '몰캠 남자 느좋 프로필 월드컵', class_type: 'all', profile_type: 'profile', gender_type: 'boy', id: 'baca62f3-930e-4a6f-94b1-54414f6855fd'},
	{name: '몰캠 여자 느좋 프로필 월드컵', class_type: 'all', profile_type: 'profile', gender_type: 'girl', id: 'ddeb8141-82d5-4e1c-bf94-3e1fb5a2be0f'},
	{name: '몰캠 전체 느좋 프사 월드컵', class_type: 'all', profile_type: 'photo', gender_type: 'all', id: '0efea519-1d04-4e21-a251-ec57e13ee022'},
	{name: '몰캠 남자 느좋 프사 월드컵', class_type: 'all', profile_type: 'photo', gender_type: 'boy', id: '012df2d7-fdac-421c-ac22-3e169abf74cc'},
	{name: '몰캠 여자 느좋 프사 월드컵', class_type: 'all', profile_type: 'photo', gender_type: 'girl', id: '176eeef3-7c5f-4f3b-94d4-6af105bd280d'},
	{name: '1분반 전체 느좋 프로필 월드컵', class_type: 'class1', profile_type: 'profile', gender_type: 'all', id: 'a14322a9-820b-4368-801e-632648bc8407'},
	{name: '1분반 남자 느좋 프로필 월드컵', class_type: 'class1', profile_type: 'profile', gender_type: 'boy', id: '5e4c117a-dc1b-48b2-b9da-d825b17082d9'},
	{name: '1분반 여자 느좋 프로필 월드컵', class_type: 'class1', profile_type: 'profile', gender_type: 'girl', id: 'c0f7215f-8731-484c-929b-93569acb328b'},
	{name: '1분반 전체 느좋 프사 월드컵', class_type: 'class1', profile_type: 'photo', gender_type: 'all', id: '79680e8d-88d0-44a5-a77c-96ebdccb9ef4'},
	{name: '1분반 남자 느좋 프사 월드컵', class_type: 'class1', profile_type: 'photo', gender_type: 'boy', id: '9e4c3fc3-d69d-4dc7-81e2-147baa083978'},
	{name: '1분반 여자 느좋 프사 월드컵', class_type: 'class1', profile_type: 'photo', gender_type: 'girl', id: 'a59f1103-594e-4a92-bdcd-cfc6b3739132'},
	{name: '2분반 전체 느좋 프로필 월드컵', class_type: 'class2', profile_type: 'profile', gender_type: 'all', id: 'd6a41f38-a211-4698-87b2-7c75f9904166'},
	{name: '2분반 남자 느좋 프로필 월드컵', class_type: 'class2', profile_type: 'profile', gender_type: 'boy', id: '32ea2e64-9efd-4562-931c-a550a9566d14'},
	{name: '2분반 여자 느좋 프로필 월드컵', class_type: 'class2', profile_type: 'profile', gender_type: 'girl', id: '208133e7-de34-476d-8d45-1ec9b9046f6e'},
	{name: '2분반 전체 느좋 프사 월드컵', class_type: 'class2', profile_type: 'photo', gender_type: 'all', id: '4a88f019-6ef1-4d33-b175-28d7c20cde5a'},
	{name: '2분반 남자 느좋 프사 월드컵', class_type: 'class2', profile_type: 'photo', gender_type: 'boy', id: '9661081c-b919-40c5-982b-4ca59f8b3a47'},
	{name: '2분반 여자 느좋 프사 월드컵', class_type: 'class2', profile_type: 'photo', gender_type: 'girl', id: '4d56a221-339e-4078-8f82-6bb1281534d6'},
	{name: '3분반 전체 느좋 프로필 월드컵', class_type: 'class3', profile_type: 'profile', gender_type: 'all', id: '90f0eecc-cb29-429c-88c5-ed6723e1a51f'},
	{name: '3분반 남자 느좋 프로필 월드컵', class_type: 'class3', profile_type: 'profile', gender_type: 'boy', id: '4552e290-4d64-43e5-8fe2-1552c06b56a0'},
	{name: '3분반 여자 느좋 프로필 월드컵', class_type: 'class3', profile_type: 'profile', gender_type: 'girl', id: 'a9f152f2-413d-4267-87a0-1eb917d1cacc'},
	{name: '3분반 전체 느좋 프사 월드컵', class_type: 'class3', profile_type: 'photo', gender_type: 'all', id: '9dabaf5d-4c8e-4e8b-9f7a-74ac75fc223e'},
	{name: '3분반 남자 느좋 프사 월드컵', class_type: 'class3', profile_type: 'photo', gender_type: 'boy', id: '5e5adc88-12a4-4ab1-963e-4423ce9ea77f'},
	{name: '3분반 여자 느좋 프사 월드컵', class_type: 'class3', profile_type: 'photo', gender_type: 'girl', id: '74639181-feae-4f72-bea1-8b1ba0e72be2'},
	{name: '4분반 전체 느좋 프로필 월드컵', class_type: 'class4', profile_type: 'profile', gender_type: 'all', id: '35a9766a-fcab-4b56-aba1-93366be036f0'},
	{name: '4분반 남자 느좋 프로필 월드컵', class_type: 'class4', profile_type: 'profile', gender_type: 'boy', id: '2b0dbe09-e6ae-4aec-8251-0b8d47efcb3f'},
	{name: '4분반 여자 느좋 프로필 월드컵', class_type: 'class4', profile_type: 'profile', gender_type: 'girl', id: '50e6c99e-7dc0-4898-9aba-dcdebf86edf4'},
	{name: '4분반 전체 느좋 프사 월드컵', class_type: 'class4', profile_type: 'photo', gender_type: 'all', id: '5bfacfa2-28f4-4ba4-9c8d-ea8d8ede64ab'},
	{name: '4분반 남자 느좋 프사 월드컵', class_type: 'class4', profile_type: 'photo', gender_type: 'boy', id: '7941622d-1d22-4bd3-bb74-fc50e9f0591a'},
	{name: '4분반 여자 느좋 프사 월드컵', class_type: 'class4', profile_type: 'photo', gender_type: 'girl', id: '4a26509d-0119-4146-a37c-7caef90367fb'}
  ]
  